In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.21.6'

# Creating array using Python list using NumPy

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a

array([1, 2, 3])

In [ ]:
list = [True, 55, "Nirajan"]

In [ ]:
list

[True, 55, 'Nirajan']

In [ ]:
type(list[0])

bool

In [ ]:
arr = np.array([True, 55, "Nirajan"])

In [ ]:
arr

array(['True', '55', 'Nirajan'], dtype='<U21')

In [ ]:
arr[0]

'True'

# How To Create Array

In [ ]:
a = np.array([17, 44, 1])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

1

In [ ]:
a = a.reshape(-1,1)

In [ ]:
a

array([[17],
       [44],
       [ 1]])

In [ ]:
a.ndim

2

In [ ]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# You can create an array with range of elements using

```
np.arange()

list(range(1,10))
```

In [ ]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

# Use linspace to create array with values that are spaced linearly in a specified interval.

In [ ]:
np.linspace(0, 0.5, 6)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5])

In [ ]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

# Concatenation and sorting two NumPy Array

In [ ]:
arr = np.array([-1, -11, 4, 77, 2, -99, 3])

In [ ]:
np.sort(arr)

array([-99, -11,  -1,   2,   3,   4,  77])

In [ ]:
np.sort(arr)[::-1]          # sorting in descending order

array([ 77,   4,   3,   2,  -1, -11, -99])

In [ ]:
a = np.array([1, 2,3,4])

In [ ]:
b = np.array([5, 6, 7, 8])

In [ ]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a+b            # adds the numbers from both the arrays that are parallel to each other

array([ 6,  8, 10, 12])

# Indexing in NumPy arrays

In [ ]:
a = np.arange(1,6)

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
a[0]

1

In [ ]:
a[2:4]

array([3, 4])

In [ ]:
a[[1, 3, 4]]     # Fancy Indexing

array([2, 4, 5])

In [ ]:
a = np.arange(1,6)

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
a[-1]     # negative indexing

5

In [ ]:
# np.any(), np.all()

a = np.array([1,2,3,4,5,6,7,6,5,4,3,2,1])

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
np.any(a>5)

True

In [ ]:
np.all(a>5)

False

In [ ]:
a > 5

array([False, False, False, False, False,  True,  True,  True, False,
       False, False, False, False])

In [ ]:
a[a>5]

array([6, 7, 6])

# Assignment:

& | ^ ~ : 

Read the above Bitwise operators

# Vector operation in NumPy array


In [ ]:
a = np.array([1,2])

In [ ]:
b = np.array([4,8])

In [ ]:
a+b

array([ 5, 10])

In [ ]:
a-b

array([-3, -6])

In [ ]:
a*b

array([ 4, 16])

In [ ]:
a/b

array([0.25, 0.25])

In [ ]:
a**2

array([1, 4])

In [ ]:
a**b

array([  1, 256])

# Broadcasting in NumPy Array

\begin{bmatrix}
1\\
2\\
6\\
\end{bmatrix}

+

\begin{bmatrix}
3
\end{bmatrix}

In [ ]:
a = np.array([1,2])

In [ ]:
a + 3          # broadcasting    --    brightness & contest (use)

array([4, 5])

# Array operation

```
np.floor()
np.ceil()
np.round()
```

In [ ]:
a = np.array([1.1, 1.5, 1.9, 2.5])

In [ ]:
np.floor(a)

array([1., 1., 1., 2.])

In [ ]:
np.round(a)

array([1., 2., 2., 2.])

In [ ]:
np.ceil(a)

array([2., 2., 2., 3.])

# Statistics using NumPy

In [ ]:
a = np.array([44, 33, 66])

In [ ]:
a.max()

66

In [ ]:
a.min()

33

In [ ]:
a.argmax()

2

In [ ]:
a.argmin()

1

In [ ]:
a.sum()

143

In [ ]:
a.std()

13.719410418171117

In [ ]:
a.var()

188.2222222222222

In [ ]:
a.mean()

47.666666666666664

In [ ]:
round(a.mean(), 2)

47.67